### ISSUE TITLE
Missing licence

### ISSUE THREAD

**Issue by domints** [Stormancer/netproxy#2]
Hi,

I'd like to use your code as a base for my little project, essentialy I'd like to proxy TCP connections from my GPS tracker to GPS tracking server, which is what your code seems to do. However I also need to intercept the traffic to log it into my database for storage redundancy and future custom processing, which your code obviously doesn't do.

Therefore I would like to use your code as a base for my app, as I would like to not have to reinvent the wheel with TCP proxying :) 

May I have your permission to use your code and publish it on github (that would make deploys easier), of course making sure you're marked as proxy code author.

**Comment by jmderuty** [comment]
Hello, I'm quite late, but starting work again on this project, so I added an MIT license file to the repo. Going to reorganize everything in the next few days too and switch to git flow.
